In [2]:
import pandas as pd
import numpy as np

In [7]:
fetal_df = pd.read_csv("C:\\Users\\sarayu krishna\\Downloads\\CTG.csv")

In [8]:
fetal_df

,FileName,Date,SegFile,b,e,LBE,LB,AC,FM,UC,...,C,D,E,AD,DE,LD,FS,SUSP,CLASS,NSP
0,Variab10.txt,12/1/1996,CTG0001.txt,240.0,357.0,120.0,120.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,9.0,2.0
1,Fmcs_1.txt,5/3/1996,CTG0002.txt,5.0,632.0,132.0,132.0,4.0,0.0,4.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0
2,Fmcs_1.txt,5/3/1996,CTG0003.txt,177.0,779.0,133.0,133.0,2.0,0.0,5.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0
3,Fmcs_1.txt,5/3/1996,CTG0004.txt,411.0,1192.0,134.0,134.0,2.0,0.0,6.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,1.0
4,Fmcs_1.txt,5/3/1996,CTG0005.txt,533.0,1147.0,132.0,132.0,4.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,S8001045.dsp,6/6/1998,CTG2127.txt,1576.0,3049.0,140.0,140.0,1.0,0.0,9.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,5.0,2.0
2125,S8001045.dsp,6/6/1998,CTG2128.txt,2796.0,3415.0,142.0,142.0,1.0,1.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
2126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,564.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
fetal_df.isna().sum()

FileName    3
Date        3
SegFile     3
b           3
e           3
LBE         3
LB          3
AC          3
FM          2
UC          2
ASTV        2
MSTV        2
ALTV        2
MLTV        2
DL          1
DS          1
DP          1
DR          1
Width       3
Min         3
Max         3
Nmax        3
Nzeros      3
Mode        3
Mean        3
Median      3
Variance    3
Tendency    3
A           3
B           3
C           3
D           3
E           3
AD          3
DE          3
LD          3
FS          3
SUSP        3
CLASS       3
NSP         3
dtype: int64

In [12]:
import numpy as np
import pandas as pd

# Assuming your dataset is in a DataFrame called df
# And 'CLASS' is the class label column

# List of features to consider (excluding 'CLASS' which is the label)
features = ['FileName', 'Date', 'SegFile', 'b', 'e', 'LBE', 'LB', 'AC', 'FM', 'UC', 'ASTV', 'MSTV', 
            'ALTV', 'MLTV', 'DL', 'DS', 'DP', 'DR', 'Width', 'Min', 'Max', 'Nmax', 'Nzeros', 'Mode', 
            'Mean', 'Median', 'Variance', 'Tendency', 'A', 'B', 'C', 'D', 'E', 'AD', 'DE', 'LD', 
            'FS', 'SUSP', 'NSP']

# Extract the class column
class_column = 'CLASS'

# Separate the data for two classes (e.g., class 3 and class 2)
class_3_data = fetal_df[fetal_df[class_column] == 3][features].values
class_2_data = fetal_df[fetal_df[class_column] == 2][features].values

# Step 1: Calculate the mean (centroid) for each class
centroid_3 = np.mean(class_3_data, axis=0)
centroid_2 = np.mean(class_2_data, axis=0)

# Step 2: Calculate the spread (standard deviation) for each class
spread_3 = np.std(class_3_data, axis=0)
spread_2 = np.std(class_2_data, axis=0)

# Step 3: Calculate the distance between the mean vectors (centroids) of the two classes
interclass_distance = np.linalg.norm(centroid_3 - centroid_2)

# Print the results
print(f"Centroid of Class 3: {centroid_3}")
print(f"Centroid of Class 2: {centroid_2}")
print(f"Spread (Standard Deviation) of Class 3: {spread_3}")
print(f"Spread (Standard Deviation) of Class 2: {spread_2}")
print(f"Interclass Distance between Class 3 and Class 2: {interclass_distance}")

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [14]:
import numpy as np
import pandas as pd

# Assuming your dataset is in a DataFrame called df
features = ['FileName', 'Date', 'SegFile', 'b', 'e', 'LBE', 'LB', 'AC', 'FM', 'UC', 'ASTV', 'MSTV', 
            'ALTV', 'MLTV', 'DL', 'DS', 'DP', 'DR', 'Width', 'Min', 'Max', 'Nmax', 'Nzeros', 'Mode', 
            'Mean', 'Median', 'Variance', 'Tendency', 'A', 'B', 'C', 'D', 'E', 'AD', 'DE', 'LD', 
            'FS', 'SUSP', 'NSP']

class_column = 'CLASS'

# Check which columns contain non-numeric data
non_numeric_columns = df[features].select_dtypes(exclude=[np.number]).columns
print("Non-numeric columns:", non_numeric_columns)

# Convert non-numeric columns to numeric, coercing errors to NaN
df[features] = df[features].apply(pd.to_numeric, errors='coerce')

# Drop rows with any NaN values
df_clean = df.dropna(subset=features)

# Verify that the data is now numeric
print("Data types after conversion:\n", df_clean.dtypes)

# Separate the data for two classes (e.g., class 3 and class 2)
class_3_data = df_clean[df_clean[class_column] == 3][features].values
class_2_data = df_clean[df_clean[class_column] == 2][features].values

# Ensure the data is not empty
if class_3_data.size == 0 or class_2_data.size == 0:
    print("One of the classes has no data after cleaning.")
else:
    # Step 1: Calculate the mean (centroid) for each class
    centroid_3 = np.mean(class_3_data, axis=0)
    centroid_2 = np.mean(class_2_data, axis=0)

    # Step 2: Calculate the spread (standard deviation) for each class
    spread_3 = np.std(class_3_data, axis=0)
    spread_2 = np.std(class_2_data, axis=0)

    # Step 3: Calculate the distance between the mean vectors (centroids) of the two classes
    interclass_distance = np.linalg.norm(centroid_3 - centroid_2)

    # Print the results
    print(f"Centroid of Class 3: {centroid_3}")
    print(f"Centroid of Class 2: {centroid_2}")
    print(f"Spread (Standard Deviation) of Class 3: {spread_3}")
    print(f"Spread (Standard Deviation) of Class 2: {spread_2}")
    print(f"Interclass Distance between Class 3 and Class 2: {interclass_distance}")

Centroid of Class 3: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan]
Centroid of Class 2: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan]
Spread (Standard Deviation) of Class 3: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan]
Spread (Standard Deviation) of Class 2: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan]
Interclass Distance between Class 3 and Class 2: nan

C:\Users\sarayu krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\sarayu krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\_methods.py:121: RuntimeWarning: divide by zero encountered in divide
  ret = um.true_divide(
C:\Users\sarayu krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
C:\Users\sarayu krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\_methods.py:206: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
C:\Users\sarayu krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\_methods.py:163: RuntimeWarning: divide by zero encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
C:\Users\sarayu krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\_methods.py:163: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
C:\Users\sarayu krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\_methods.py:195: RuntimeWarning: divide by zero encountered in divide
  ret = um.true_divide(
C:\Users\sarayu krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\_methods.py:195: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(